name: Rust Build and Test

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest # You can choose a different runner if needed
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4.2.1

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: cargo build

      - name: Unit Test
        run: cargo test